config/routes.rb
Vk::Application.routes.draw do
  root to: 'welcome#index'

  resource :session, only: [ :destroy, :update ] do
    get :callback, on: :member
  end

  scope module: 'authenticated' do
    resources :groups, only: [ :index, :show, :destroy ] do
      put :update, on: :collection

      resources :auto_exchanges, only: [ :index, :create, :update ]
      resource  :auto_exchanges_search, only: [ :new, :create ]
    end

    resources :posts, only: [ :update, :create, :destroy ]
    get '/posts/:id' => 'posts#index', as: 'group_posts'

    resources :photos, only: [ :index, :create ]

    resources :schedules, only: [ :create, :destroy, :update ]
    get '/schedules/:id' => 'schedules#index', as: 'group_schedules'

    get 'profile' => 'users#show', as: 'user'
  end

end

app/models/auto_exchanges_search.rb
class AutoExchangesSearch
  include Enumerable

  DEFAULT_SORT = 'posts.created_at DESC'

  class << self
    def create params, order = DEFAULT_SORT
      new(params, order).tap { |search| search.send(:fetch_results!) }
    end

    def sortable_attributes
      %w(subscribers_count views_count visitors_count reach reach_subscribers)
    end

    def sortable_directions
      %w(asc desc)
    end
  end

  attr_accessor :posts, :order

  def initialize attrs, order = DEFAULT_SORT
    @groups = Group.arel_table
    @posts = []
    @order = order

    attrs.each do |key, value|
      instance_variable_set :"@#{key}", value
      self.class.send :attr_accessor, key.to_sym
    end
  end

  def each &block
    fetch_results! unless @results.any?

    @results.each(&block)
  end

  private

  def fetch_results!
    groups = Group.all.select(:id).tap do |results|
      results.where!(conditions_for(:subscribers_count)) if processible_attributes?(:subscribers_count)
      results.where!(conditions_for(:views_count)) if processible_attributes?(:views_count)
      results.where!(conditions_for(:visitors_count)) if processible_attributes?(:visitors_count)
      results.where!(conditions_for(:reach)) if processible_attributes?(:reach)
      results.where!(conditions_for(:reach_subscribers)) if processible_attributes?(:reach_subscribers)
    end

    @posts = Post.unscoped.where(available_for_exchanges: true, group_id: groups.pluck(:id)).
      joins(:group).
      order(order).
      includes(:group)
  end

  def processible_attributes? attr
    one_of_pair_attributes_present?(attr) and valid_pair?(attr)
  end

  def valid_pair? attr
    min, max = instance_variable_get(:"@min_#{attr}"), instance_variable_get(:"@max_#{attr}")
    return true if min.nil? or max.nil?

    if min >= max
      instance_variable_set :"@max_#{attr}", nil
      true
    end
  end

  def one_of_pair_attributes_present?(attr)
    instance_variable_get(:"@min_#{attr}").present? or instance_variable_get(:"@max_#{attr}").present?
  end

  def conditions_for attr
    min, max = instance_variable_get(:"@min_#{attr}"), instance_variable_get(:"@max_#{attr}")

    ( min.present? and max.present? ) ? _between(attr, min, max) : _resolve_pair(attr, min, max)
  end

  def _between attr, min, max
    { attr => [min..max] }
  end

  def _resolve_pair attr, min, max
    min.present?? @groups[attr].gteq(min) : @groups[attr].lteq(max)
  end
end

app/controllers/authenticated/auto_exchanges_controller.rb
class Authenticated::AutoExchangesController < Authenticated::BaseController
  before_filter :find_group!

  def index
  end

  def create
  end

  def update
  end

  private

  def find_group!
    @group = current_user.groups.find(params[:group_id])
  end
end

app/controllers/authenticated/auto_exchanges_searches_controller.rb
class Authenticated::AutoExchangesSearchesController < Authenticated::BaseController
  before_filter :find_group!

  def new
    @posts = current_user.posts.available_for_exchanges
  end

  def create
    @group.update auto_exchange_conditions: auto_exchanges_search_params
    @auto_exchanges_search = AutoExchangesSearch.create(auto_exchanges_search_params, order)

    render json: { results: render_to_string(partial: 'auto_exchanges_search', collection: @auto_exchanges_search.posts, as: 'post') }
  end

  private

  def find_group!
    @group = current_user.groups.find(params[:group_id])
  end

  def auto_exchanges_search_params
    params.require(:auto_exchanges_search).permit(:min_subscribers_count, :max_subscribers_count, :min_views_count, :max_views_count,
                                                  :min_visitors_count, :max_visitors_count, :min_reach, :max_reach,
                                                  :min_subscribers_reach, :max_subscribers_reach).

                                                  delete_if { |key, value| value.to_i < 1 }
  end

  def auto_exchanges_search_sort_params
    params.require(:auto_exchanges_search).permit(:sort_attribute, :sort_direction).tap do |attrs|
      attrs[:sort_attribute] = nil unless AutoExchangesSearch.sortable_attributes.include?(attrs[:sort_attribute])
      attrs[:sort_direction] = nil unless AutoExchangesSearch.sortable_directions.include?(attrs[:sort_direction])
    end
  end

  def order
    attrs = auto_exchanges_search_sort_params
    return nil unless attrs[:sort_attribute].present? and attrs[:sort_direction].present?

    "groups.#{ attrs[:sort_attribute] } #{ attrs[:sort_direction] }"
  end
end

app/controllers/authenticated/base_controller.rb
class Authenticated::BaseController < ApplicationController
  layout 'authenticated'

  before_filter :authenticate_user!

  def current_user_vk
    @current_user_vk ||= VkontakteApi::Client.new(current_user.token)
  end
end

app/controllers/authenticated/groups_controller.rb
class Authenticated::GroupsController < Authenticated::BaseController
  before_filter :find_group!, only: [ :show, :destroy ]

  def index
    @groups = current_user.groups
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: { group: render_to_string(partial: 'show_group') }, status: 200 }
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_path }
      format.json { render nothing: true, status: 202 }
    end
  end

  def update
    groups  = current_user_vk.groups.get(extended: 1, filter: 'admin').tap { |groups_list| groups_list.shift }

    groups.each do |group|
      group_attributes = group_params(group)

      if current_user.groups.where(vk_id: group_attributes[:vk_id]).any?
        current_user.groups.find_by(vk_id: group_attributes[:vk_id]).update group_attributes
      else
        current_user.groups.create(group_attributes)
      end
    end

    current_user.groups.each do |group|
      Thread.new { group.refresh_info! }
    end

    respond_to do |format|
      format.html { redirect_to groups_path, notice: I18n.t('flash.authenticated.groups.update.notice') }
      format.json do
        render json: { groups: render_to_string(partial: 'group', collection: current_user.groups), message: I18n.t('flash.authenticated.groups.update.notice') },
               status: 202
      end
    end
  end

  private

  def find_group!
    @group = Group.find(params[:id])
  end

  def group_params(attributes)
    { vk_id: attributes[:gid], name: attributes[:name], screen_name: attributes[:screen_name],
      photo_urls: attributes.slice(:photo, :photo_medium, :photo_big), group_type: attributes[:type],
      active: attributes[:is_closed].zero? }
  end
end

app/controllers/authenticated/photos_controller.rb
class Authenticated::PhotosController < Authenticated::BaseController
  before_filter :find_photo!, only: [ :destroy ]
  before_filter :find_group!, only: [ :index ]

  def destroy
    @photo.destroy
  end

  def create
    server_details = current_user_vk.photos.get_wall_upload_server
    file_path      = Rails.root.join('public', 'uploads', photo_params.original_filename).to_s

    begin
      with_temporary_file file_path, photo_params.open.read do
        uploaded_photo_details = VkontakteApi.upload(url: server_details[:upload_url], photo: [ file_path, photo_params.content_type ])
        saved_photo_details    = current_user_vk.photos.save_wall_photo(uploaded_photo_details).first

        @photo = current_user.photos.create(urls: saved_photo_details.slice(:src, :src_big, :src_small, :src_xbig),
                                            info: saved_photo_details.slice(:id, :owner_id, :pid, :aid))
      end

      render json: { photo: render_to_string(partial: 'photo', locals: { photo: @photo }) }, status: 202
    rescue
      render json: { error: I18n.t('flash.authenticated.photos.create.alert') }, status: 422
    end
  end

  def index
    @group
  end

  private

  def find_photo!
    @photo = current_user.photos.find(params[:id])
  end

  def find_group!
    @group = current_user.groups.find(params[:group_id])
  end

  def photo_params
    params.require(:photo)[:image]
  end

  def with_temporary_file path, content
    File.open(path, 'w') { |file| file.write content }
    yield
    File.delete path
  end
end

app/controllers/authenticated/posts_controller.rb
class Authenticated::PostsController < Authenticated::BaseController
  before_filter :find_post!, only: [ :update, :destroy ]
  before_filter :find_group!, only: [ :index, :create ]
  before_filter :validate_photo_ids!, only: [ :create, :update ], unless: -> { repost? }

  def index
    @posts  = @group.posts.page(params[:page])
    @photos = current_user.photos.all
    @post   = @group.posts.new
  end

  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to group_path(@post.group), notice: I18n.t('flash.authenticated.posts.destroy.notice') }
      format.json { render nothing: true, status: 202 }
    end
  end

  def update
    respond_to do |format|
      if @post.update post_params
        format.html { redirect_to group_path(@post.group), notice: I18n.t('flash.authenticated.posts.update.notice') }
        format.json { render json: { entry: render_to_string(partial: 'post', locals: { post: @post }), id: @post.id }, status: 202 }
      else
        format.html { redirect_to group_path(@post.group), notice: I18n.t('flash.authenticated.posts.update.alert') }
        format.json { render json: { errors: @post.errors }, status: 422 }
      end
    end
  end

  def create
    if repost?
      if valid_repost?
        @post = @group.posts.create(repost_params)
      else
        @post = Post.new.tap { |post| post.errors.add(:vk_details, I18n.t('activerecord.errors.models.post.attributes.vk_details.invalid')) }
      end
    else
      @post = @group.posts.create(post_params)
    end

    respond_to do |format|
      if @post.persisted?
        format.html { redirect_to group_path(@group), notice: I18n.t('flash.authenticated.posts.create.notice') }
        format.json { render json: { entry: render_to_string(partial: 'post', locals: { post: @post }) }, status: 202 }
      else
        format.html { redirect_to group_path(@group), notice: I18n.t('flash.authenticated.posts.create.alert') }
        format.json { render json: { errors: @post.errors }, status: 422 }
      end
    end
  end

  private

  def find_post!
    @post = current_user.posts.find(params[:id])
  end

  def find_group!
    @group = if action_name == 'index'
               current_user.groups.find(params[:id])
             else
               current_user.groups.find(post_params[:group_id])
             end
  end

  def post_params
    if params[:post].present?
      params.require(:post).permit(:body, :group_id, :from_group, photo_ids: [])
    else
      params.permit(:available_for_exchanges)
    end
  end

  def repost_params
    params.require(:post).permit(:vk_details, :body).tap do |attributes|
      wall_id, post_id = attributes[:vk_details].scan(/\d+_\d+/).last.split('_')

      attributes[:vk_details] = { url: attributes[:vk_details], wall_id: wall_id, post_id: post_id }
      attributes[:repost]             = true
    end
  end

  def repost?
    params[:post].present? and params[:post][:repost] == 'true'
  end

  def valid_repost?
    params[:post].try(:[], :vk_details) =~ /\d+_\d+/
  end

  def validate_photo_ids!
    return if params[:post].try(:[], :photo_ids).nil?

    if params[:post].present?
      params[:post][:photo_ids] = _validated_photo_ids(params[:post][:photo_ids])
    elsif params[:edit_post].present?
      params[:edit_post][:photo_ids] = _validated_photo_ids(params[:edit_post][:photo_ids])
    end
  end

  def _validated_photo_ids id_list
    current_user.photos.select('photos.id').where(id: id_list.split(',').map(&:to_i).uniq).pluck(:id)
  end
end

app/controllers/authenticated/schedules_controller.rb
class Authenticated::SchedulesController < Authenticated::BaseController
  before_filter :find_schedule!, only: [ :destroy, :update ]
  before_filter :find_post!, only: [ :create, :index ]

  def index
    @schedules = @post.schedules

    render json: { schedules: render_to_string(partial: 'schedule', collection: @schedules) }, status: 200
  end

  def create
    @schedule = @post.schedules.create(schedule_params)

    respond_to do |format|
      if @schedule.persisted?
        format.html { redirect_to group_path(@post.group), notice: I18n.t('flash.authenticated.schedules.create.notice') }
        format.json { render json: { entry: render_to_string(partial: 'schedule', locals: { schedule: @schedule }) }, status: 202 }
      else
        format.html { redirect_to group_path(@post.group), alert: I18n.t('flash.authenticated.schedules.create.alert') }
        format.json { render json: { errors: @schedule.errors }, status: 422 }
      end
    end
  end

  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to posts_path, notice: I18n.t('flash.authenticated.schedules.destroy.notice') }
      format.json { render nothing: true, status: 202 }
    end
  end

  def update
    # publish now!
  end

  private

  def find_schedule!
    @schedule = current_user.schedules.find(params[:id])
  end

  def find_post!
    @post = if action_name == 'index'
              @post = current_user.posts.find(params[:id])
            else
              @post = current_user.posts.find(schedule_params[:post_id])
            end
  end

  def schedule_params
    params.require(:schedule).permit(:post_at_date, :post_at_time, :post_id).tap do |attrs|
      if attrs[:post_at_date].present? and attrs['post_at_time(4i)'].present? and attrs['post_at_time(5i)'].present?
        month, day, year = attrs.delete(:post_at_date).split('/')

        attrs['post_at(1i)'], attrs['post_at(2i)'], attrs['post_at(3i)'], attrs['post_at(4i)'], attrs['post_at(5i)'] = year, month, day, attrs['post_at_time(4i)'], attrs['post_at_time(5i)']
        attrs.delete_if { |key, value| key =~ /post_at_time/ }
      else
        attrs.delete_if { |key, value| key =~ /post_at/ }
        attrs[:post_at] = Time.now
      end
    end
  end
end

app/controllers/authenticated/users_controller.rb
class Authenticated::UsersController < Authenticated::BaseController
  def show
  end
end

app/helpers/authenticated/auto_exchanges_helper.rb
module Authenticated::AutoExchangesHelper
end

app/helpers/authenticated/auto_exchanges_searches_helper.rb
module Authenticated::AutoExchangesSearchesHelper
  def stored_condition attr
    @group.auto_exchange_conditions[attr.to_s] if @group.auto_exchange_conditions?
  end

  def sort_button attr
    link_to icon_label('', t(".sortings.#{attr}")), nil, class: 'btn', data: { sort_attribute: attr, sort_direction: 'desc' }
  end
end

app/helpers/authenticated/photos_helper.rb
module Authenticated::PhotosHelper
end

app/helpers/authenticated/posts_helper.rb
module Authenticated::PostsHelper
  def repost_content(post)
    "<span class='label label-info'>#{ t('.repost_from') }</span>: #{post.vk_details['url']}".html_safe
  end
end

app/helpers/authenticated/schedules_helper.rb
module Authenticated::SchedulesHelper
end

app/views/authenticated/auto_exchanges_searches/_auto_exchanges_search.erb
<div class='search-result row'>
  <div class='span6'>
    <div class='post alert alert-info'>
        <div class='body'><%= simple_format(post.body) %></div>

        <div class='post-photos'>
          <% post.photos.each do |photo| %>
            <div class='post-photo' id='post-photo-<%= photo.id %>'><%= image_tag photo.urls['src_small'] %></div>
          <% end %>
        </div>
    </div>
  </div>

  <div class='span6 group-info'>
    <strong> <%= post.group.name %> </strong>

    <div><span> <%= t '.info.subscribers' %> </span>: <strong class='label label-info'> <%= post.group.subscribers_count %> </strong></div>
    <div><span> <%= t '.info.views' %> </span>: <strong class='label label-info'> <%= post.group.views_count %> </strong></div>
    <div><span> <%= t '.info.visitors' %> </span>: <strong class='label label-info'> <%= post.group.visitors_count %> </strong></div>
    <div><span> <%= t '.info.reach' %> </span>: <strong class='label label-info'> <%= post.group.reach %> </strong></div>
    <div><span> <%= t '.info.reach_subscribers' %> </span>: <strong class='label label-info'> <%= post.group.reach_subscribers %> </strong></div>
  </div>
</div>

<hr>

app/views/authenticated/auto_exchanges_searches/new.html.erb
<% content_for :page_header do %>
  <%= page_header(t '.header', name: @group.name) %>
<% end %>

<%- if @posts.none? %>
  <div class='alert alert-danger'>
    <i class='icon-exclamation-sign'></i> <%= t '.no_posts' %>

    <hr />

    <%= link_to t('.group_posts', name: @group.name), group_posts_path(@group) %>
  </div>
<% end %>

<%= link_to icon_label('icon-ange-up', t('.new')), nil, class: 'btn btn-info', id: 'new-search-form-toggler' %>

<div id='new-search-form-container'>
  <%= simple_form_for :auto_exchanges_search, url: group_auto_exchanges_search_path(@group), remote: true, html: { id: 'new-search', class: 'form-horizontal' } do |form| %>
    <div class='controls-row'>
      <%= form.input :min_subscribers_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:min_subscribers_count) } %>
      <%= form.input :max_subscribers_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:max_subscribers_count) } %>
    </div>

    <div class='controls-row'>
      <%= form.input :min_views_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:min_views_count) } %>
      <%= form.input :max_views_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:max_views_count) } %>
    </div>

    <div class='controls-row'>
      <%= form.input :min_visitors_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:min_visitors_count) } %>
      <%= form.input :max_visitors_count, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:max_visitors_count) } %>
    </div>

    <div class='controls-row'>
      <%= form.input :min_reach, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:min_reach) } %>
      <%= form.input :max_reach, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:max_reach) } %>
    </div>

    <div class='controls-row'>
      <%= form.input :min_subscribers_reach, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:min_subscribers_reach) } %>
      <%= form.input :max_subscribers_reach, as: :integer, wrapper_class: 'span5', input_html: { value: stored_condition(:max_subscribers_reach) } %>
    </div>

    <%= form.input :sort_attribute, as: 'hidden' %>
    <%= form.input :sort_direction, as: 'hidden' %>

    <%= form.button :submit, t('.submit'), class: 'btn-success', data: { disable_with: t('common.please_wait') } %>
  <% end %>
</div>

<hr>

<div id='search-results-sortings-container'>
  <% AutoExchangesSearch.sortable_attributes.each do |sort_option| %>
    <%= sort_button(sort_option) %>
  <% end %>
</div>

<div id='no-results'>
  <h3><%= t '.no_results' %></h3>
</div>

<div id='search-results'>
</div>