config/routes.rb
Vk::Application.routes.draw do
  root to: 'welcome#index'

  resource :session, only: [ :destroy, :update ] do
    get :callback, on: :member
  end

  scope module: 'authenticated' do
    resources :groups, only: [ :index, :show, :destroy ] do
      put :update, on: :collection

      resources :auto_exchanges, only: [ :index, :create, :update ]
      resource  :auto_exchanges_search, only: [ :new, :create ]
    end

    resources :posts, only: [ :update, :create, :destroy ]
    get '/posts/:id' => 'posts#index', as: 'group_posts'

    resources :photos, only: [ :index, :create ]

    resources :schedules, only: [ :create, :destroy, :update ]
    get '/schedules/:id' => 'schedules#index', as: 'group_schedules'

    get 'profile' => 'users#show', as: 'user'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include VkAuthenticable
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate!

  private

  def authenticate!
    authenticate_or_request_with_http_basic do |user_name, password|
      session[:admin] = ( user_name == ENV['VK_LOGIN'] and password == ENV['VK_PASSWORD'] )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_header(text = t('.header'))
    "<div class='page-header'> <h3> #{ text } </h3> </div>".html_safe
  end

  def icon_label(classes, text = '')
    "<i class='#{ classes }'></i> #{ text }".html_safe
  end

  def dom_id(*args)
    super.dasherize
  end

  def vk_group_url group
    'http://vk.com/' + group.screen_name
  end

  def highlight_links text
  end
end

app/views/application/_footer.erb
 <div id="footer">
  <div class="container">
    <div class="muted message"> <%= t '.message' %> </div>
  </div>
</div>

app/views/application/_header.erb
<div class="navbar" id='header'>

  <div class="navbar-inner">
    <%= link_to t('.brand'), root_path, class: 'brand', data: { 'no-turbolink' => true } %>

    <ul class="nav">
      <li class='<%= "active" if current_page?(root_path) %>'> <%= link_to t('.root'), root_path %> </li>

      <%- if user_signed_in? %>
        <li class='<%= "active" if current_page?(user_path) %>'> <%= link_to t('.profile'), user_path %> </li>
      <% end %>
    </ul>

    <ul class='nav pull-right'>
      <%- if user_signed_in? %>
        <li> <%= link_to icon_label('icon-signout', t('.sign_out')), session_path, method: 'delete' %> </li>
      <% else %>
        <li> <%= link_to icon_label('icon-signin', t('.sign_in')), @vk_url %> </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/application/_notifications.erb
<div class='container'>

  <div id='notifications'>
    <%- if flash[:notice].present? %>
      <div class='alert alert-info'>
        <button type="button" class="close" data-dismiss="alert"> <%= t 'common.x' %> </button>
        <h4> <%= t 'common.heads_up!' %> </h4>

        <%= flash[:notice] %>
      </div>
    <% end %>

    <%- if flash[:alert].present? %>
      <div class='alert alert-error'>
        <button type="button" class="close" data-dismiss="alert"> <%= t 'common.x' %> </button>
        <h4> <%= t 'common.warning!' %> </h4>

        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

</div>